### ISSUE TITLE
Question: Working Demo Example?

### ISSUE THREAD

**Issue by TornMarketing** [MinnPost/object-sync-for-salesforce#102]
Hey Team,

I have been trying to get the plugin work for the last few hours, loving the concept but really need a working example to figure out why things are happening as I expect.

Questions:
1. What determines and updates the value lists for Wordpress and Salesforce? I seem to be only able to get new values by completely uninstalling the plugin then reinstalling, I was expecting it to get fresh fields everytime you look at the object much like you can with the Gravity Forms Salesforce plugin
2. I had an instance where the table 'object_sync_sf_field_map' wasn't installing but object_sync_sf_object_map was, is there any known reasons why this may have been an issue. 
I managed to install it but it was on a clean WordPress, first time I have ever experienced an issue like that.
3. Is there ability to set static string values for fields? ie status, record type or standard elements again similar to Gravity Forms Salesforce plugin
4. Filter logic for results to push/pull, ie I have a products table but I only want to pull in the active products, Ability to pull custom SOQL queries
5. Has anyone had any experience with mapping out Woocommerce products? Product attributes, photos, bundled products and the like? Really would love and appreciate anyone's assistance to help prior learnings.

**Comment by jonathanstegall** [comment]
Hello,

I can try to answer some of these:

1. I'm not entirely sure if this is what you are asking about, but the plugin does not (currently, at least) retrieve data that exists before the plugin does. That is, it looks for new data, from both systems, going forward from its initial install, rather than retroactively syncing data objects that might already exist. You can see more about this in the [syncing setup](https://github.com/MinnPost/object-sync-for-salesforce/blob/master/docs/syncing-setup.md) of the documentation. It would be possible to manually create database rows, though, to track updates. If the object types are already mapped in the `object_sync_sf_object_map` table, you would need a SQL query something like this: `INSERT INTO `wp_object_sync_sf_object_map` (`wordpress_id`, `salesforce_id`, `wordpress_object`, `created`, `object_updated`, `last_sync`, `last_sync_action`, `last_sync_status`, `last_sync_message`)VALUES('wordpress-id', 'salesforce-id', 'wordpress-object-type', '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0000-00-00 00:00:00', NULL, 0, NULL);`
2. I should note that the plugin will delete both these tables when it is deactivated, so back up if you need to save any data, but I would try to reinstall the plugin if this happens, and see if MySQL returns any errors. The plugin will always try to create (or update) both those tables when it is activated.
3. You could certainly use a developer hook for this and create a plugin to do it. The plugin has many many hooks for things like this.
4. Developer hooks would be ideal for this as well. The plugin's philosophy is that those kind of things don't belong in the core, as we could never possibly account for all the variations that might be done. But the hooks are powerful, and hopefully [reasonably well documented](https://github.com/MinnPost/object-sync-for-salesforce/blob/master/docs/all-developer-hooks.md).
5. I haven't used any myself, but I think there are some plugins specifically built for WooCommerce/Salesforce. I ran across this one sometime ago: https://github.com/Neuralab/WooCommerce-Salesforce-integration. But there's certainly no reason our plugin could not do this syncing as well. As far as I know, no one has done it yet , but do let us know if you try it. I've actually just created a [section of our documentation](https://github.com/MinnPost/object-sync-for-salesforce/blob/master/docs/example-extending-plugins.md) for the purpose of listing plugins that use our developer hooks.

I hope I'm understanding your questions, and if so hope the answers help.

**Comment by jonathanstegall** [comment]
It's been a week, so will close this issue tomorrow if there's no further need for discussion. Happy to continue if so, though. I think it's possible the plugin is usable for you as is, but certainly is also possible that you'd need developer extensions for it to be viable; I'm unclear on that.
