### ISSUE TITLE
Question: Refresh fields from Salesforce (feature would be manual cache expire edit and/or refresh)

### ISSUE THREAD

**Issue by mcculloughcm** [MinnPost/object-sync-for-salesforce#106]
Hi folks, I'm testing your plugin and it's super exciting -- thanks for your work!

I had a question -- in the course of testing, I created a few new fields in Salesforce that I wanted to add to a field mapping. But I haven't been able to get them to show up -- I'm guessing the initial object describe results for Contact are cached somewhere. Is there a way to force a refresh? I've tried re-Authorizing, and even unisintalling/reinstalling, but no cigar. 

Similarly, we've added a few custom fields to the User in Wordpress, and I'm not seeing those either.

Thanks!

**Comment by mcculloughcm** [comment]
OK I've had partial success -- I got the Salesforce fields to update by changing the API version ans changing it back.

**Comment by mcculloughcm** [comment]
Well, that wasn't quite true. I switched from API v40 to v39 and the fields were re-pulled. But when I switched back to v40, it seems like it went back to the old cached version. So I'd still love to know if there's a way to force a refresh.

**Comment by jonathanstegall** [comment]
@mcculloughcm well, the plugin will clear the cache on its own based on the `object_sync_for_salesforce_cache_expiration` row in the `wp_options` table. By default that value is 86400 seconds, or 1 day.

You could certainly change that value manually, although currently we don't have a method within the interface to change it or to force a refresh.

I'm inclined to think there are three possible ways of doing that:

1. Put in a developer hook to change that option value (this would be the least difficult since we don't have to organize how it fits into the interface).
2. Put an option value somewhere in the plugin Settings tab so users can tell it how long to save the cache (I'm not necessarily opposed to this but I do worry about having too many settings already).
3. Put a button somewhere to clear the cache entirely (I'm not necessarily opposed to this either, but it is more complicated).

We could do any/all of those things, but it might be a while before we got to it (we're not doing as much dedicated work on this plugin right now). For your immediate need, I suppose you have two options:

1. Wait 12 hours until it clears
2. If you are comfortable with MySQL, you can delete the cache rows there yourself (that is where they are stored, assuming you are not already using a cache plugin of some kind). They'll end up having an unhelpful `option_name` of something like `_transient_93ec7c8f81de2a367978a94e770acbd9`, but you should be able to see cached JSON for your various Salesforce data in the `option_value` and could maybe delete the relevant rows there. If you are using a cache plugin like Super Cache or Total Cache, that plugin will, I think, have its own ways of clearing itself that should relate to this plugin's data as well.

**Comment by mcculloughcm** [comment]
Thanks @jonathanstegall, deleting the cache manually will work. 

I think a refresh button would be great eventually -- maybe on the Fieldmaps list view? For me at least, it's pretty common that I discover a field I need to add once I start setting up a sync.

Thanks again for your help.

**Comment by jonathanstegall** [comment]
@mcculloughcm that does make a lot of sense. I imagine many people could use this plugin while they're doing an initial Salesforce setup.

I've added a branch for this at https://github.com/MinnPost/object-sync-for-salesforce/tree/106-refresh-cache.

Off the top of my head, I think we'd just have to start to prefix all of the transients this plugin creates (probably should've done that from the beginning) so they can be identified ("find all transients that start with `_transient_sf_sync_` and delete them" or something similar). So it's maybe not that complicated.

**Comment by jonathanstegall** [comment]
Although now that I think more about it, the complexity comes in where we have to check and see if it is cached somewhere other than `wp_options`. So if it's a cache plugin, or memcache, or whatever. Presumably WordPress has ways of facilitating this, but it'll be another layer of stuff.

**Comment by jonathanstegall** [comment]
Complicated indeed. Some info for myself to remember about deleting by prefix (for our needs here, at least, anything we might implement for this has to support object caching):

https://wordpress.org/ideas/topic/transient-api-should-allow-delete-by-prefix

> In retrospect, this isn't all that great an idea. Basically, it would work for installations with no object cache, where it's easy to query the database for transients with a specific prefix, but could not possibly work with some persistent object caches such as memcached. This is because you can't query memcached or some other object caches with anything other than an exact ID match.
>
> What I do instead is implement a caching layer on top of either transients or the object cache, detecting whether an object cache is present. If there's an object cache, I add a salt to the cache key and change the salt when I want to clear all items -- i.e. the items are "forgotten" because the cache keys all change when the salt changes. If there's no object cache, I use transients with a given prefix so that I can delete then en masse as per the Idea above.
>
> In short: the transients API can't do this, because some storage mechanisms won't support it. If you need to do this, do it yourself.

**Comment by jonathanstegall** [comment]
To see if anything comes of it, I added a StackExchange question for this issue. https://wordpress.stackexchange.com/questions/278127/clearing-cached-plugin-data-if-it-is-using-an-external-object-cache

**Comment by jonathanstegall** [comment]
https://core.trac.wordpress.org/ticket/4476

**Comment by jonathanstegall** [comment]
@mcculloughcm hi, I've released an update to this plugin that allows for clearing the plugin's cache data. It is on the Fieldmap list page; I think your suggestion of putting it there was perfect.
