### ISSUE TITLE
sObject type FAQ_Subscribers__ka is not replicable

### ISSUE THREAD

**Issue by bada815** [MinnPost/object-sync-for-salesforce#109]
Hello, 
I have installed and setup this plugin in my salesforce sandbox instance, But keep generate an error log as like below  
"URL: https://cs53.salesforce.com/services/data/v40.0/sobjects/FAQ_Subscribers__ka/deleted/?start=2017-09-06T08:16:43Z&end=2017-09-06T08:17:51Z
Message: sObject type FAQ_Subscribers__ka is not replicable
 Code: 400 "

I'm not sure what the problem is caused, 

- Authorize is passed after salesforce settings. 
- FieldMaps settings
Action trigger is  only enable WordPress create  and not select any salesforce related. 
Please advise.

**Comment by jonathanstegall** [comment]
@bada815 

In general, a 400 error means: `The request couldn’t be understood, usually because the JSON or XML body contains an error.` This means when the plugin tries to retrieve data from Salesforce (which is required by the WordPress create trigger; this is how it syncs the data) it returns an error.

Some possible reasons:

1. I see that the URL you are calling seems to be for deleted items. Some record types are retrievable once they've been deleted, but others are not. This is a Salesforce thing; it is not about this plugin.
2. I am not familiar with FAQ_Subscribers_ka as a content type. It is possible that it is not retrievable at all (some objects aren't: see https://developer.salesforce.com/forums/?id=906F00000008pm2IAA for example).

I expect it's one of those: either that type can't be retrieved at all, or it can't be retrieved once the items have been deleted. I would recommend investigating this further at the Salesforce forums or at the Salesforce StackExchange site.

**Comment by jonathanstegall** [comment]
I'll mark this issue closed once it has been open for 7 days, if there are not further things for us to investigate.
