### ISSUE TITLE
Trying to Sync Newly created field with Salesforce

### ISSUE THREAD

**Issue by pixelparlordev** [MinnPost/object-sync-for-salesforce#130]
Hi,

I don't think this is an issue or anything bad, but I am trying to do something custom and I am just wondering if anyone else has this issue, or if there is a way to initiate this. 

I am using a plugin called memberpress to manage a membership site I am building. Then I am syncing the user objects with Salesforce via this plugin. 

I was able to figure out a way to create a new field that represents the user level by reflecting the status which is output by a transaction table. 

I added this function which creates the new field within the WP user object, which is great.

However I am not seeing the newly created field showing up in fieldmaps area of my WP objects. It shows all the default WP fields, and I have cleared the plugin cache. So I am just wondering if I need to do something extra to get object sync to map a field that I created via functions.php. 

Code Example:

```
function sync_membership_to_field($event) {
  $obj = $event->get_data();

  if(!($obj instanceof MeprTransaction) && !($obj instanceof MeprSubscription)) {
    return; // nothing here to do if we're not dealing with a txn or sub
  }

  $user = $obj->user();

  if($user) {
    $subs = $user->active_product_subscriptions('products');

    if(!empty($subs)) {
      update_user_meta($user->ID, 'mepr_subscription_name', $subs[0]->post_title);
    }
    else {
      update_user_meta($user->ID, 'mepr_subscription_name', 'None');
    }
  }
}
add_action('mepr-event-create', 'sync_membership_to_field');
```

**Comment by jonathanstegall** [comment]
@pixelparlordev hello. I'm not familiar with this particular plugin, but the first thing I would ask is whether you have any users that have data for the new field(s)?

This plugin can access all user meta fields that are added by core WordPress methods, but not until those fields have data. In other words, if there are users in the database, and there's a meta field, but none of the users have a value for that particular meta field, the plugin can't see it.

This is an unfortunate effect of how WordPress handles fields (we have it documented in this issue: #119). So first, I'd try to make sure you have a value in that field, and then clear the cache for this plugin's data again. I expect you'll see the field then.

If you don't see it after that, do comment again. It might be that this plugin creates its fields in a non-standard way. We do have hooks for that (for example [https://github.com/MinnPost/object-sync-for-salesforce/blob/master/docs/extending-parameters.md](here) is some documentation).

Hopefully one of those will be helpful.

**Comment by rwdevpixelparlor** [comment]
Hey Jonathan. I was able to map nearly everything from wordpress to salesforce. Which is great. So, with this code --
```
function sync_membership_to_field($event) {
  global $wpdb;
  $obj = $event->get_data();

  if(!($obj instanceof MeprTransaction) && !($obj instanceof MeprSubscription)) {
    return; // nothing here to do if we're not dealing with a txn or sub
  }

  $user = $obj->user();

  if($user) {
    $subs = $user->active_product_subscriptions('products');
    
    if(!empty($subs)) {
      $expires_at = $wpdb->get_var("SELECT expires_at FROM {$wpdb->prefix}mepr_transactions WHERE user_id = {$user->ID} ORDER BY ID DESC LIMIT 1");
      if($expires_at) {
        update_user_meta($user->ID, 'mepr_subscription_expiration', $expires_at);
      }
      else {
        update_user_meta($user->ID, 'mepr_subscription_expiration', 'No Active Subscriptions');
      }
      update_user_meta($user->ID, 'mepr_subscription_name', $subs[0]->post_title);
    }
    else {
      update_user_meta($user->ID, 'mepr_subscription_expiration', 'No Active Subscriptions');
      update_user_meta($user->ID, 'mepr_subscription_name', 'None');
    }
  }
}
add_action('mepr-event-create', 'sync_membership_to_field');
```

-- I am able to map both Member level & Member Expiration from the same table. So I am nearly there because I can map both fields from that table in object sync, and I can see the member level show up in salesforce. However, I can't make the expiration date sho up in salesforce. Even though I can see it in my object sync settings, and I am not getting any errors after clearing the plugin cache.

Would this have something to do with weight or anything?

Here is a screengrab:
 
<img width="1479" alt="screen shot 2018-01-25 at 4 59 47 pm" src="https://user-images.githubusercontent.com/31666816/35414825-a662590c-01f1-11e8-89a1-b6d4cd262b38.png">

<img width="354" alt="screen shot 2018-01-25 at 5 03 38 pm" src="https://user-images.githubusercontent.com/31666816/35414847-b7a03ff4-01f1-11e8-8d32-3f6500400481.png">

<img width="569" alt="screen shot 2018-01-25 at 5 03 57 pm" src="https://user-images.githubusercontent.com/31666816/35414859-c1ccadd2-01f1-11e8-8a06-2f9d9077056b.png">

If anything seems off to you, please comment. Like I said I am not seeing errors, so I intend to investigate all day tomorrow.

Have a nice day.

**Comment by jonathanstegall** [comment]
@rwdevpixelparlor are you saying the only field you are still unable to map is the expiration date field? If so, are you sure that the two fields have the same format? Salesforce can be picky about dates, I've found. It might not be that but that might be a good thing to investigate, if the only field that is not syncing correctly is a date field.

**Comment by rwdevpixelparlor** [comment]
I was thinking the same thing. I noticed that there are no errors actually logging, but when I try to push from the member's dash in salesforce, I get some picklist error.

It looks fine when I click push to salesforce, since I am only concerned with pushing one way for the trickier fields. 

<img width="709" alt="screen shot 2018-01-26 at 10 29 02 am" src="https://user-images.githubusercontent.com/31666816/35446856-08de0f6c-0284-11e8-9bc1-1ce4dc9f8ae9.png">

But when I hit update I get this,

<img width="711" alt="screen shot 2018-01-26 at 10 24 24 am" src="https://user-images.githubusercontent.com/31666816/35446897-212ac510-0284-11e8-9e0b-73861d3d1f3d.png">

So now I am actually further behind than I was yesterday because now the member levels won't sync.

I googled this "Membership Level: bad value for restricted picklist field:"
and someone said to uncheck "Restrict picklist to the values defined in the value set",but I have no idea where that is. 

So I guess first thing is to make the member level syncing work again. And then try to get back to where I was.

**Comment by rwdevpixelparlor** [comment]
So by deleting the expiration date fields, and making a new member (every single time I need to reconfigure something), I was able to again sync the member level to salesforce. But as soon as I change the level and re-push to salesforce, nothing updates on the salesforce side. It's like it will only sync once, and then thats it, which seem weird.

**Comment by jonathanstegall** [comment]
@rwdevpixelparlor restricted picklists are a bit of a beast in Salesforce. When I ran into it trying to figure out if it was the plugin or Salesforce, here's what worked for me: https://github.com/MinnPost/object-sync-for-salesforce/issues/128#issuecomment-353088409

**Comment by rwdevpixelparlor** [comment]
Yeah I definitely want to fiddle with this today, seems like it should help. Right now I'm so confused becasue I was able easily sync the member level with a pick-list with no issue. It was only one way WP > SF, but now that just magically stopped syncing and no settings have been changed.

**Comment by rwdevpixelparlor** [comment]
I have temporarily went back to trying to sync the member levels by using the first chunk of code from the very beginning of this thread, since it seems to be a bigger issue that these fields only write once and can't be updated or overwritten once in salesforce. The only thing that has changed on the wordpress or salesforce side is that this plugin seems to have been updated. Would there be anything new that would now prevent this? The stranger thing is that even if I delete the criteria within that field, and re-push, salesforce pulls in the old member level. 

These are my settings, I have no idea what could even be causing this as there aren't any errors.

<img width="1662" alt="screen shot 2018-01-26 at 12 08 37 pm" src="https://user-images.githubusercontent.com/31666816/35451585-bbe64f54-0291-11e8-8832-4ca6493482bd.png">

**Comment by jonathanstegall** [comment]
Nothing here looks off, to me. Are any log entries being created, and/or mapping error entries?

**Comment by rwdevpixelparlor** [comment]
No errors. This is exactly the same thing I was working with two weeks ago, and now it just doesn't work quite as well.  I have no idea why the levels only sync once. Before I could sign up a new member, they would pick a level of membership during sign up, and it would sync immediately to salesforce. Then I could go into their account, change the level, and the it would change on the salesforce side after I pushed from, their settings.

**Comment by jonathanstegall** [comment]
There is nothing extra you should have to do. I'll try to look further into this and see if I can duplicate the issue.

**Comment by jonathanstegall** [comment]
Have you tried resaving the fieldmap? You don't necessarily have to add another field or anything, just resave it and see if it helps.

I don't think this is necessarily the issue, but it is worth a try. Then clear the plugin cache again.

**Comment by rwdevpixelparlor** [comment]
Thanks, very sorry to bother you so much. However I am just working with no roadmaps here and I was hoping to solve this expiration date problem, now I come to find my levels only syn once.

**Comment by rwdevpixelparlor** [comment]
Yeah I have been serial resaving, plugin cache clearing, and double checking everything

**Comment by jonathanstegall** [comment]
In your code, I see you have the following:

```
function sync_membership_to_field($event) {
  global $wpdb;
  $obj = $event->get_data();

  if(!($obj instanceof MeprTransaction) && !($obj instanceof MeprSubscription)) {
    return; // nothing here to do if we're not dealing with a txn or sub
  }

  $user = $obj->user();

  if($user) {
    $subs = $user->active_product_subscriptions('products');
    
    if(!empty($subs)) {
      $expires_at = $wpdb->get_var("SELECT expires_at FROM {$wpdb->prefix}mepr_transactions WHERE user_id = {$user->ID} ORDER BY ID DESC LIMIT 1");
      if($expires_at) {
        update_user_meta($user->ID, 'mepr_subscription_expiration', $expires_at);
      }
      else {
        update_user_meta($user->ID, 'mepr_subscription_expiration', 'No Active Subscriptions');
      }
      update_user_meta($user->ID, 'mepr_subscription_name', $subs[0]->post_title);
    }
    else {
      update_user_meta($user->ID, 'mepr_subscription_expiration', 'No Active Subscriptions');
      update_user_meta($user->ID, 'mepr_subscription_name', 'None');
    }
  }
}
add_action('mepr-event-create', 'sync_membership_to_field');
```

Why not try to do some error logging here? If you have access to your server's error logs, do some `error_log('show messages')` at different spots and see what it shows. I am not familiar with the memberpress plugin you are using, but it does look like your `sync_membership_to_field` function only seems to run when an event is created. So it would only update the user's meta value once?

In any case, if you can log each time it is supposed to update the user's meta, maybe you can see what is happening. The Salesforce plugin probably won't ever see this data except when the `update_user_meta` function runs.

**Comment by rwdevpixelparlor** [comment]
Good idea, I think you nailed it with the idea that -
"your sync_membership_to_field function only seems to run when an event is created. So it would only update the user's meta value once?"

I can confirm that I am having no issue with normal fields like if I change a member's employee count or annual revenue for example. So thats all fine. Fortunately I have a pretty good line of contact with memberpress devs so maybe I can ask if there is a more functional way to keep the fields from this transaction table synced with SF.

**Comment by jonathanstegall** [comment]
If they have additional hooks, you might find it easier to use one of our hooks as well. For example https://github.com/MinnPost/object-sync-for-salesforce/blob/master/docs/extending-parameters.md can be helpful. We do have a full list of hooks as well, at https://github.com/MinnPost/object-sync-for-salesforce/blob/master/docs/all-developer-hooks.md.

**Comment by rwdevpixelparlor** [comment]
Awesome! Yeah I will hammer it out with them for a bit. It seems that if it were an issue with your product, none of the fields would sync, which isn't the case. I forwarded them your suggestions and maybe I can come up with something. I think it boils down to the fact that a member level can't just be a field like other criteria because there needs to be some way to authenticate via transactions. I guess the point of this is to protect against fraud since each level of membership is a differently priced product. 

Thanks so much for the help so far.

**Comment by jonathanstegall** [comment]
@rwdevpixelparlor how is this going? Did you get it resolved?

**Comment by pixelparlordev** [comment]
Yeah I got everything working the way we wanted (so far). I was really able to open up the possibilities after I learned more about Memberpress fields and how to sync them with fields of similar formats in Salesforce. I really appreciate all of your help so far. Your product is amazing btw. 

As far as basic syncing goes I think I am good? The next thing I will be tackling is syncing sub accounts in memberpress.  However I think that will go much smoother now that I have my bearings.
