### ISSUE TITLE
Field Limits

### ISSUE THREAD

**Issue by prowp** [MinnPost/object-sync-for-salesforce#140]
Is there a field limit when creating field maps? I keep getting a non-descript error when saving a high number of fields in a field map. An error block appears but there is no message, and the field map is wiped out. I've rebuilt a couple of times and it keeps happening at a certain point. 

### Expected behavior
Fields save

### Actual behavior
field map fields get wiped out, error block appears that is blank

### Steps to reproduce behavior
I will have to try to figure out the number where it fails to see if it's consistent.

**Comment by jonathanstegall** [comment]
@prowp there certainly isn't an intentional field limit. The database uses a TEXT field to store the field pairings. In MySQL, this field can apparently store up to 65,535 characters. I suppose it's possible the plugin stores enough for each pairing that you've gone above this limit?

If you have access to your database, you could try the following SQL and see if it fixes the issue. If it does, I'd happily change the plugin to work this way:

```
ALTER TABLE wp_object_sync_sf_field_map MODIFY fields LONGTEXT;
```

(Of course change the `wp` prefix to your own if you use something different.)

Otherwise, the only thing I can think of is to check your server and/or database error logs. I guess there might be something in there that WordPress doesn't know what to do with.

**Comment by prowp** [comment]
I'm going to guess that you've figured out the problem correctly. With 5 fields in the map, the character count in the field is approaching 10k, I think I was losing it somewhere between 20 and 30 fields. I am going to make the change rebuild the list and report back.

**Comment by prowp** [comment]
I made the database change, and re-entered my fields (70) and there was no problem. This may be an edge case, I'm not sure many people will be syncing that amount of fields, but making the change in the next version would be a good move. I appreciate the response as always.

**Comment by prowp** [comment]
Adding an additional comment here. Since yesterday I'm having issues with fields not updating after sync. 

I'm adding it to this thread because this is the only thing that changed that I'm aware of in the past 24 hours. 

Using the WP Debug log didn't give me any useful info. The php error log just says: PHP Warning: checkdate() expects parameter 1 to be long, string given, and that occurs during the cron run. Not sure if it's relevant, but just adding all the information.

I put the plugin itself in debug mode, it successfully pulls a record that's been modified, the field data is correct, and then I get a successful update message for the matching post_id, but the data isn't updated. 

Do you have a good starting point to troubleshoot this?

**Comment by jonathanstegall** [comment]
@prowp I'm not sure. I've been trying to see if I can get this issue to happen myself, but so far I've been unable.

I'm curious what happens if you downgrade the plugin to 1.2.4? You can download old versions at https://wordpress.org/plugins/object-sync-for-salesforce/advanced/. If the issue does not happen in 1.2.4, maybe there's an issue with your environment updating to 1.2.5. It's maybe still hard to identify, since 1.2.5 might have already made database updates, but at least we can start there.

**Comment by prowp** [comment]
I tracked down this problem through some perseverance.

I am seeing new items get added without a problem, but the updates are just dying, but indicating success in logging. 

The process is dying after a call to wp_update_post. The error is invalid date: 

The content array is this: 
array(4) {
  ["ID"]=>
  string(4) "7766"
  ["post_date"]=>
  string(16) "January 24, 2018"
  ["post_modified"]=>
  string(16) "January 29, 2018"
  ["post_type"]=>
  string(7) "product"
}

The error that gets kicked back is this:
object(WP_Error)#3504 (2) {
  ["errors"]=>
  array(1) {
    ["invalid_date"]=>
    array(1) {
      [0]=>
      string(13) "Invalid date."
    }
  }
  ["error_data"]=>
  array(0) {
  }
}

Logging just shows a successful update.

**Comment by jonathanstegall** [comment]
I see, that makes sense. I'm surprised it logs it as a successful entry. I've made a separate issue for this, both because it doesn't log as it should and because I think the param mapping should be able to format dates the way WordPress wants them. This issue is #142.
