### ISSUE TITLE
Issue with Authorize

### ISSUE THREAD

**Issue by ltlmschrisss** [MinnPost/object-sync-for-salesforce#145]
### Expected behavior
Authorize success
### Actual behavior
Error 0:
### Steps to reproduce behavior
I followed the instructions for setup on the salesforce and woocommerce

**Comment by jonathanstegall** [comment]
This is a Salesforce error. Some questions:

1. Have you followed all the instructions here? https://github.com/MinnPost/object-sync-for-salesforce/blob/master/docs/initial-setup.md Especially check the permissions in the Salesforce app.
2. How long has the app in Salesforce existed? Sometimes it takes a few minutes for the app to be fully setup in Salesforce.
3. Do you have any server log entries?

**Comment by ltlmschrisss** [comment]
Yes, I did follow the instructions on that documentation. The app has been set up for at least an hour. When I turned on the log the error is Error: 0: on Salesforce http request. I have triple checked the address and its correct on both the salesforce app side and the woo commerce side.

**Comment by jonathanstegall** [comment]
I've seen Salesforce return error 0 from time to time. In my experience it has been because the connection was down, or the SSL was incorrect. If you don't have issues with either of those, I think you'll need to contact Salesforce.

**Comment by ltlmschrisss** [comment]
Ok, when you say the SSL was incorrect does this mean a problem with the s portion of our https on the woo commerce side? They just got that set up recently. (before I did this though)

**Comment by ltlmschrisss** [comment]
Also, thank you so much for your help!

**Comment by jonathanstegall** [comment]
WooCommerce doesn't require SSL, but Salesforce requires it to authorize a connection to this plugin. This means the server where WordPress is running has to have SSL, regardless of what WooCommerce is doing.

**Comment by ltlmschrisss** [comment]
Ok, our site starts with https:// but ill reach out just to make sure that everything in the background is complete and good. Thank you again!

**Comment by jonathanstegall** [comment]
It may have nothing to do with that, but otherwise I expect you'll have to contact Salesforce and see what they have to say. The error certainly comes from the Salesforce side.

**Comment by ltlmschrisss** [comment]
Ok, so they made some changes on the site side and now I am getting a different error
Error 400: grant type not supported

**Comment by jonathanstegall** [comment]
This is also a Salesforce error. I can tell you that when we were developing the plugin, we had to assign this to the curl request headers during authentication: `Content-Type: application/x-www-form-urlencoded` to get rid of this error. There's more discussion about this all over the Salesforce forums (for example here: https://developer.salesforce.com/forums/?id=906F00000008nFOIAY). But since this is already included in the plugin, it's possible your server has curl issues.

It also looks like sometimes people continue to see this error if some of the data Salesforce requires for authentication is not being passed.

You may want to deactivate the plugin and reactivate it and make sure you put in all the settings correctly, just to see if that changes anything.

**Comment by martian77** [comment]
I'm seeing the same 400 error when I try to authorise my new app, and actually in the request_token function in classes/salesforce.php the line to add the content type to the header is commented out. Although it looks like it's been removed for about a year now and uncommenting hasn't fixed my issue, so maybe not.

**Comment by jonathanstegall** [comment]
In my test site, I was able to get this error by deleting my app from Salesforce. Then WordPress receives a 400 error, although it is not the same error message.

After that I went through the process to add another app in Salesforce.

My settings in Salesforce look like this:

![test](https://user-images.githubusercontent.com/435342/36311499-179f3da0-12f1-11e8-8627-cd476ab93384.png)

I waited a few minutes, and went to add the settings in WordPress.

- Consumer Key: (from Salesforce)
- Consumer Secret: (from Salesforce)
- Callback URL: https://vanilla-wordpress.test/wp-admin/options-general.php?page=object-sync-salesforce-admin&tab=authorize
- Login Base URL: https://test.salesforce.com (this test site goes to a sandbox)
- Authorize URL Path: /services/oauth2/authorize
- Token URL Path: /services/oauth2/token
- Salesforce API Version: 42.0

I saved, and then went to Authorize. I signed in to Salesforce, and it came back and successfully authenticated.

I'm not sure what is happening with either of your installs. @martian77, I wonder if your Salesforce app was not yet initialized? It does take several minutes. I'm not sure, otherwise?

As you say, that line in the `request_token` method isn't necessary. It does get used in `refresh_token` but I can't remember why it all went down that way.

**Comment by martian77** [comment]
I finally did figure this out. I had the wrong Login base url set. I'd taken it from the URL of the Salesforce instance _after_ I'd logged in (https://{client_name}.lightning.force.com rather than https://{client_name}.cs86.my.salesforce.com), and it turns out that using that caused a 302 redirect, which makes the POST for the token into a GET, which failed. 

Not your code at all, and a very misleading error message from Salesforce. I only worked it out when I tried to recreate the calls using Postman. 

I eventually noticed that the login URL in the email I got to verify my SF account was different, so on the off chance that helps someone else, look there!

I really appreciate your responding to this - many thanks!

**Comment by jonathanstegall** [comment]
Ahh, I see. What I've done in my setups is use https://login.salesforce.com (for production) or https://test.salesforce.com (for a sandbox) as the base URL. This does work, which I think is especially helpful in case Salesforce decides to move your instance to another server. Salesforce appears to be able to handle the redirects on its own, that way.

I think this is in the documentation, but I think it is not as clear as it should be, and should also be in the interface. I'll put that in in the next release, I think.

I am not a fan of the Salesforce error messages, myself. It is a mixed bag, at best.

**Comment by ltlmschrisss** [comment]
This was also solved for me when I used the standard login url. Thanks!
