### ISSUE TITLE
405 Error

### ISSUE THREAD

**Issue by ltlmschrisss** [MinnPost/object-sync-for-salesforce#150]
### Expected behavior
Syncing
### Actual behavior
Only will push to salesforce on manual push after removing the temporary mapping from the original error
### Steps to reproduce behavior
A new user gets created on WooCommerce and it errors on the original system sync

<p>URL: https://vayapharma.my.salesforce.com/services/data/v41.0/sobjects/Contact/Email/</p><p>Message: HTTP Method &#039;PATCH&#039; not allowed. Allowed are GET,HEAD,POST</p><p>Code: 405

**Comment by jonathanstegall** [comment]
Patch is used to update records in Salesforce. I'm not sure why it is trying to run an update if the item does not exist.

Some things to investigate:

- What are your fieldmap trigger settings?
- Does it fail in the same way with asynchronous enabled as it does with it disabled?
- Does it work if you try to pull from Salesforce?

When you say "A new user gets created on WooCommerce and it errors on the original system sync" I'm assuming you mean a new WordPress user - I don't think WooCommerce has its own separate users? Or are you trying to sync customers?

**Comment by jonathanstegall** [comment]
Also, please close your previous issue if it has been resolved.

**Comment by ltlmschrisss** [comment]
Ok, I closed the previous issue. I think the primary issue here is that I am really clueless on wooommerce as I am the Salesforce Admin. Does anyone have a basic listing of appropriate mapping of the woocommerce objects to SF? Ultimately we are going to be syncing the "order" portion of the data down to opportunities and opportunity line items. I have been unsure how the object sync knows to map the related objects too. Any help is greatly appreciated!

**Comment by jonathanstegall** [comment]
The first thing I should say is that Object Sync for Salesforce doesn't have built in support for WooCommerce. It kind of supports it, to the extent that WC uses WordPress' default ways of creating objects and data. WooCommerce is very complicated, and on top of that it often deviates from default WordPress methods, and it's certainly possible that this plugin won't support it when it does.

That doesn't mean you can't use them together, but it does mean this plugin is not intentionally built for that purpose (we didn't include because many people don't use WooCommerce - we don't use it ourselves).

This plugin has abundant developer hooks though, if you have access to a developer who is really skilled with WooCommerce, it would totally be possible to build an add-on plugin to provide full support (we would happily link to it for all users who install this plugin while they're running WooCommerce, but we wouldn't include such code in this plugin, since so many people don't use WooCommerce). WooCommerce has a large API as well; my suspicion is that one would have to use our hooks and the WooCommerce API to build a solid integration. But I don't use WooCommerce, so I don't know for sure.

I'll see if I can answer any of these, from the little bit of testing I've done with WooCommerce:

1. A basic listing of appropriate mapping of WooCommerce to SF depends entirely on what you need in Salesforce and how your Salesforce is configured. There are so many different ways to use both that I think it would be really hard to create a default for this.
2. But as you say, you want Orders to Opportunities. Even among opportunities, the structure is quite different, but for example, here's how an opportunity works for us:

- Object Sync for Salesforce can pick the default opportunity type (default, for example)
- You can sync post title to Opportunity Name 
- _paid_date to Close date (this is when the payment processes, so it fits how we use it)
- _order_total to Amount
- post_status to Stage (I think this might require some use of the developer hooks to change the values to match the ones in Salesforce)
- our SF requires a Primary Campaign, and I think you'd have to use code for this. I'm not aware of any equivalent in WooCommerce, although maybe there is one.
- _payment_method to Payment Type

In our Salesforce, those are the only required fields for an opportunity. We have a lot of fields that might be custom for address and such, like this:

- _billing_first_name to Donor first name
- _billing_last_name to Donor last name
- _billing_first_name to Donor first name
- _billing_address_1 to Donor address 1
- _billing_address_2 to Donor address 2
- _billing_city to Donor city
- _billing_state to Donor state
- _billing_postcode to Donor zip
- _billing_email to Donor email
- _billing_country to Donor country
- _billing_phone to Donor phone
(same basic idea for shipping address)

But again, we don't use WC, so I haven't worked with this.

3. Object Sync for Salesforce does not do anything with related objects automatically. You certainly can map related objects the same way you map primary objects, but it doesn't do this on its own. You could also do it via developer hooks, if there wasn't an object <-> object map.

Anyway, you could certainly try mapping orders with something like the above, but I think it's certainly possible that to use the two plugins together effectively is going to require some add-on code. WC just does so many things in its own, non-default, ways.

**Comment by ltlmschrisss** [comment]
Thank you so much for the clarification.
