### ISSUE TITLE
Email field won't populate on first pull

### ISSUE THREAD

**Issue by mcculloughcm** [MinnPost/object-sync-for-salesforce#158]
I have a fieldmap of Salesforce Contacts to Wordpress Users.  Our goal is to create a Wordpress user when a Contact in Salesforce becomes a "member" (which entails updating some fields on the Contact). I've set the "Date field to trigger pull" to a custom datetime field called "Wordpress User Sync Date" that gets updated to NOW() whenever a relevant change to the membership occurs. 

This is mostly working as we hoped, except that in some cases, the user_email field in Wordpress doesn't get populated on the first sync. The user gets created, all of the other fields in my fieldmap get populated, but not user_email -- which means that the Wordpress registration email doesn't get sent. 

Even odder, the Wordpress user name does gets set to the email address (which is only mapped to the user_email field).

If I update the "Wordpress User Sync Date" in Salesforce so that the Contact is pulled again, user_email will be pulled on the subsequent sync. Similarly, if I manually pull the Contact from Salesforce after the initial sync, user_email will be pulled.

If I look at the log, it just says "Success: Create user with ID of 42 (Salesforce Contact Id of 003o000000NRJkkAAH)" -- no indication of a problem.

It seems like this only happens when a pre-existing Contact is updated -- if the contact in Salesforce  is newly created, Email syncs as expected.

In trying to figure this out and looking back through the documentation, I see that it says "Both of these directions act upon any matching data that is created after the plugin is installed." I took this to mean that the "Date field to trigger pull" is set to a time after the install, not the actual Created Date of the record in Salesforce. And I would assume that if this were my problem, the record wouldn't be created at all in Wordpress -- it wouldn't just be missing a single field out of many.

Am I misunderstanding something, or do you have any ideas?

**Comment by jonathanstegall** [comment]
Let me see if I understand what you're saying. It sounds like the flow is like this:

1. A Contact that exists in Salesforce, but is not mapped to a user in WordPress, gets updated in Salesforce.
2. The plugin retrieves data on its next pull run and realizes it needs to create an object map for this updated Contact.
3. It creates a new user in WordPress, but it fails to populate the user_email field.
4. It sends the user_login value from WordPress to Salesforce.
5. On subsequent pulls, it updates the user_email field in WordPress with the mapped value from Salesforce.

Is this right?

And are you saying that if you add a new Contact in Salesforce, it works correctly instead? So the issue is consistently with Contacts that already existed and were not mapped with WordPress objects?

**Comment by mcculloughcm** [comment]
Yes, that's exactly right.

**Comment by jonathanstegall** [comment]
Ok, that is helpful. One more question: can you tell me how that field is mapped?

That is, it could be like this image, but you may have other settings?

![image](https://user-images.githubusercontent.com/435342/38146445-9f9416d4-3413-11e8-99a7-19824bd891b8.png)

Also, what triggers do you have enabled for the fieldmap?

**Comment by mcculloughcm** [comment]
My field map matches that exactly (except that it's not first in the list, it's actually near the bottom). 

Here are my triggers:
![image](https://user-images.githubusercontent.com/1189915/38147015-54c8ed86-3405-11e8-9e54-a90b1cc34c2e.png)

**Comment by jonathanstegall** [comment]
I can replicate this issue, so hopefully I can find a fix for it. I'm not yet sure why it's happening, but when I can find a fix I'll release a plugin update.

I did want to explain one thing you mention:

> Even odder, the Wordpress user name does gets set to the email address (which is only mapped to the user_email field).

This is an intentional choice on how to handle pull requests that create new users. The `user_login` field is populated with the email address in the event that `user_login` is empty but `user_email` is populated. This allows the user to be created without WordPress throwing errors. (If there is already a parameter for `user_login`, it uses that for `user_login` instead).

It's perhaps not the most intuitive way of handling that issue, but since WordPress treats email addresses as unique, and perhaps most people would store a username in Salesforce if they expected it to be mapped, it at least gives a workable default.

**Comment by jonathanstegall** [comment]
I've figured out what causes this, actually.

In the wordpress.php class, in [these lines](https://github.com/MinnPost/object-sync-for-salesforce/blob/master/classes/wordpress.php#L835-L840), this code runs:

```
foreach ( $params as $key => $value ) {
	if ( 'wp_insert_user' === $value['method_modify'] ) {
		$content[ $key ] = $value['value'];
		unset( $params[ $key ] );
	}
}
```

I notice that if I change it to:

```
foreach ( $params as $key => $value ) {
	if ( 'wp_insert_user' === $value['method_modify'] || 'wp_update_user' === $value['method_modify'] ) {
		$content[ $key ] = $value['value'];
		unset( $params[ $key ] );
	}
}
```

The email address is saved as it should be when the Salesforce record is updated.

I need to do a bit more investigation to figure out why it was like this in the first place to make sure that changing it doesn't cause unforeseen issues. But this could be a fix, in any case.

**Comment by mcculloughcm** [comment]
Thank you so much for your responsiveness and for solving the problem!
