### ISSUE TITLE
Users not being synced to SF on Memberpress Signup

### ISSUE THREAD

**Issue by pixelparlordev** [MinnPost/object-sync-for-salesforce#187]
### Expected behavior
New Users Sign up on Memberpress, they get synced over to Salesforce with a SF ID

### Actual behavior
New Users Sign up on Memberpress, they get saved as a tmp_ user, but only until we clear mapping errors and manually repush

### Steps to reproduce behavior
Signing up for any membership level.

The only thing I can think that would be blocking this is that offline payments need to be manually approved by admin (so maybe the MP Admin Approval lag is creating this?), but it also seems to be happening to new users with CC payment, so that wouldn't make sense. 

After we clear the mapping errors and re-push, the user syncs as expected.

**Comment by jonathanstegall** [comment]
I've just started to look into this, but I'm kind of surprised it works on the sandbox if I understand correctly what is happening.

Here's my understanding:

1. A person signs up as a member
2. One of the `wp_usermeta` fields, `mepr_company_name` is created from the form they fill out, which itself is mapped to the Account Name field in Salesforce.
3. The user is not successfully pushed to Salesforce because the Account Name field is missing at the time of the push.

You can see this in the error log posts like this:

> Error: Create Account  (WordPress user with ID of 379)
> Required fields are missing: [Name]

If I'm correct in this, the reason this is happening is because the `wp_usermeta` fields are not created until immediately after the user is registered in WordPress. This is a (terrible, in my opinion) factor of the way WordPress handles users and their metadata. But in any case, the plugin tries to push the user to Salesforce before the meta field Salesforce wants is actually created, so it is unable to successfully complete.

I'm very curious if and how this particular issue worked in the sandbox, but assuming there isn't another underlying factor, I'll try and list some possible solutions:

1. You could possibly write an add-on plugin that gets the form value of the `mepr_company_name` if it is not already saved in WordPress, and adds it to the parameters. Making sure that you only do this when the value is not already present would help the efficiency, but it would also (( think) fix the issue on creating records.
2. You could instead only allow push to happen when a user is updated. This is a little more dependent on how Memberpress works, because I can't be entirely sure if the user itself is updated when the meta field is added. But if it is, when a user is registered the plugin would ignore it, but then when the meta fields are added (or the user is updated) the plugin would see it and sync it to Salesforce. But again, that might be riskier.

I'm inclined to think 1 is a possibly viable solution. There might be other solutions as well, especially depending on what happens in the sandbox.

**Comment by pixelparlordev** [comment]
Hey Jonathan,

This is very interesting to hear. I think I understand what you mean.

A bit of quick background as we’ve done a lot of experimenting during this process:

When we were working on an earlier sandbox provided by the salesforce company that we were working with (which which worked for most of the development phase, then stopped after they switched the sandbox.) I was syncing the user_login with the salesforce account ID. At some point the user_login was switched to business name to have a more accurate SF ID. So that is why it is currently set to sync that way. I’m not married to any specific way it is setup if there are issues coming from it.

As for what you said about creating an addon. Member press provided me with a snippet to place in my functions PHP file that allowed for us to sync member sign up date, level, and expiration so we could sync with Salesforce. Should business name be added in the same way? Or is this something that requires a bit more work? If this is something the we’d need make, could you possibly point me in the direction of something similar that you’ve seen? I think I could probably do it if I had some sort of reference point. Though I am not sure how common that is.

For your first suggestion, what would be the specific risks in setting it up that way? Would proper syncing just hinge on the admin manually updating the user after each sign up regardless of payment type? This seems like it might be tricky because offline payments need to be manually approved, but credit card payments through stripe do not.

The current test sandbox we have has a far looser set up. Lately we have just been using it to ensure that a new sign up his written to salesforce as a new user without any errors. Which I didn’t think I saw but there’s a chance I may have not noticed it.

I am up for either option, my main concern is to give the client a product that works and execute this project in a way the satisfies everyone. I defer to your expertise on how to best handle this. I am definitely up for trying anything though.

Also -
What are your thoughts on this Andrew?

**Comment by jonathanstegall** [comment]
In the event that the above is indeed a viable solution, I worked up a quick example of how it might work in a gist. It's possible this would need some modification, but I think it's worth checking to see if it solves the issue. Ideally with the sandbox first, but that is complicated if the sandbox does not have the issue.

https://gist.github.com/jonathanstegall/74b791f7d2bf7cea0f1268d820a41c6d

**Comment by pixelparlordev** [comment]
Hey Jonathan,

I am unfortunately away from a computer today, but I plan on giving this a shot tomorrow as soon as I get home. I can say that it is fairly easy to sync a new sign up to our test salesforce sandbox, and either me or Andrew can get you access to that and the test Dev site if you think it will clear things up for you, in terms of your grasp on the situation.

Just a random thought on the difference between live production and the sandbox. Do you think it could be something as simple as changing our main field for how we are syncing accounts to something other than business name? Or is it definitely a more complex issue than that? This just popped in my head when you mentioned that you were provided just might not work if the test sandbox is working different then the production environment. So I’m just curious what you think about that.

Thanks,

**Comment by pixelparlordev** [comment]
I am unfortunately away from a computer today, but I plan on giving this a shot tomorrow.

Just a random thought on the difference between live production and the sandbox. Do you think it could be something as simple as changing our main field for how we are syncing accounts to something other than business name? Or is it definitely a more complex issue than that? This just popped in my head when you mentioned that you were provided just might not work if the test sandbox is working different then the production environment. So I’m just curious what you think about that.

**Comment by jonathanstegall** [comment]
Sure. The main issue right now, as far as I can see, is that `mepr_company_name` is a `wp_usermeta` field instead of a `wp_users` field. If you used, for example, `display_name` which is a `wp_users` field, that would likely also fix it.

**Comment by jonathanstegall** [comment]
Sorry, I was referring to any field inside the `wp_users` database table, rather than the `wp_usermeta` table. so `user_login` would be an example because it is inside the `wp_users` table.

**Comment by pixelparlordev** [comment]
So, I am playing with this plugin, because I think we have to stick with the mepr_company_name field somehow, so we can properly sync the company name in case they pick a funky user name. Unless there is some safe way to first sync the user_login and then sync the mepr_company_nam, but that seems dangerous or a misuse of object sync.

The plugin doesn't seem to give me any errors on a local copy I have. So I am wondering if it needs modified at all? I could be wrong on this. I don't think the same issue exists in the sandbox from what I saw, so I don't know if I'd be able to test it out on there and see and changes?

**Comment by jonathanstegall** [comment]
I think it's possible it does not have to be modified, I would just tend to be overly cautious since it's a live site. I do think I would still test it in the sandbox first, just to make sure the server doesn't do anything odd with the form value of that field, or anything else unexpected when the plugin is enabled. Especially since I think you said something about the sandbox using fields that aren't `meper_company_name`. You should try to exactly duplicate the production configuration in the sandbox.

Testing it in the sandbox would let you make sure that the `mepr_company_name` field always gets pushed when a new user is created, as a Salesforce account create will always fail if whatever is being mapped to that Name field is not there.

**Comment by pixelparlordev** [comment]
It turns out that changing the main point of syncing for SF Account names to something that from the inside the wp_users table fixed syncing on signup. Just adding this in case anyone ever hits this roadblock in their own Memberpress / SF driven site.
