### ISSUE TITLE
Sync always creates new record

### ISSUE THREAD

**Issue by nodakjones** [MinnPost/object-sync-for-salesforce#200]
I'm pulling records from SF to WP.  It seems from your documentation (https://github.com/MinnPost/object-sync-for-salesforce/blob/master/docs/syncing-setup.md) that I should set a field that holds the SF Record ID in my mapping and use this field for upserts?

### Expected behavior
When a record is changed in SF, existing WP records should be updated

### Actual behavior
When a record is changed in SF, always a new records is being created in WP

### Steps to reproduce behavior
1.  Set up mapping per attached image
2.  Create record in SF
3.  Observe that record is created in WP
4.  Update record address in SF
5.  New record is created in WP instead of updating existing record.

<img width="1748" alt="screen shot 2018-09-27 at 10 24 43 am" src="https://user-images.githubusercontent.com/86551/46163285-a0b8e480-c23f-11e8-9f42-bdefa080e014.png">

**Comment by nodakjones** [comment]
For the Salesforce pull process, In your docs it says, "Upsert is used with the Prematch field defined above (the Salesforce Key field is ignored on pull operations)".  So, this tells me I need to set a prematch field.  We are getting the the ID from SF into our external_id_from_sf field so that is working correctly.  I realize per your documentation that the Salesforce Key is ignored, so I didn't need that checked.  I've tried multiple combinations of Direction, but it seems that I really just need Salesforce to Wordpress.  Also, I've checked the asynronous because it sounded like on another issue that was potentially a problem.  I'd prefer to not have to jump into a hook to further define my sync criteria because it seems this should work out of the box... I'm just missing something simple?  Thank you so much for your help!

**Comment by nodakjones** [comment]
Also, the debug log is showing: Success: Upsert WordPress duplexes with ID of 19303 (Salesforce Duplex__c Id of a00f400000E40gHAAR).  However, 19303 is a new record (post with post type of duplexes).  So, it was not Upserted, but Inserted.

**Comment by jonathanstegall** [comment]
@nodakjones I think you've found a bug here that happens when trying to match against post metadata fields.

I should be able to have a fix for this in the next few days. Possibly tomorrow, but early next week if not. Do you have any interest in testing the fix via GitHub before we release a new plugin version?

**Comment by nodakjones** [comment]
Yes. I’d be happy to test.  

Eric C Jones  

Managing Partner  
Data Imagery
data-imagery.com(http://www.data-imagery.com)
eric@data-imagery.com(mailto:eric@data-imagery.com)  
253-461-1110(tel:253-461-1110)

**Comment by jonathanstegall** [comment]
@nodakjones great. I've got a branch for this issue [here](https://github.com/MinnPost/object-sync-for-salesforce/tree/200-prematch-against-meta-fields). I'd love to see if it behaves as expected for you.

**Comment by nodakjones** [comment]
Thanks!  I downloaded the branch into my plugins dir and when I activated, I got the following error:

Warning: require(/var/www/duplexesoftexas.com/public_html/wp-content/plugins/object-sync-for-salesforce-200-prematch-against-meta-fields/vendor/prospress/action-scheduler/action-scheduler.php): failed to open stream: No such file or directory in /var/www/duplexesoftexas.com/public_html/wp-content/plugins/object-sync-for-salesforce-200-prematch-against-meta-fields/vendor/composer/autoload_real.php on line 66

Thoughts?

**Comment by jonathanstegall** [comment]
Do you know how to use composer? You can fix by running `composer install` in a command line to install the libraries. It'll be tricky to test via GitHub without that, but let me give it some thought.

**Comment by jonathanstegall** [comment]
@nodakjones Ok, you can download from [that branch](https://github.com/MinnPost/object-sync-for-salesforce/tree/200-prematch-against-meta-fields) now, and it will have all the composer libraries without you needing to install them.

**Comment by nodakjones** [comment]
Oh. Sorry. Got composer to work. But syncing stopped so I’m troubleshooting that now.  

Eric C Jones  

Managing Partner  
Data Imagery
data-imagery.com(http://www.data-imagery.com)
eric@data-imagery.com(mailto:eric@data-imagery.com)  
253-461-1110(tel:253-461-1110)

**Comment by nodakjones** [comment]
Yes, drafts was a part of the problem.  We handled this by setting a default field in salesforce with a value of publish and then synced that field over in the mappings.  Now it seems it is finding the correct post id for an upsert, but it giving an error and not actually doing the update.  Unfortunately the error is very vague:

Object: duplexes with ID of 26122

Message: Array
(
[0] => Array
(
[key] => external_id_from_sf
[value] => Array
(
[value] => a00f400000E43zoAAB
[method_modify] => update_post_meta
[method_read] => get_post_meta
)

)

)

**Comment by jonathanstegall** [comment]
Thanks for trying this. I'm assuming the title of the error log was something like "Error syncing: pull to WordPress (Salesforce [object name] Id [sf id])" and then the message body was what you pasted.

If that is correct, I'm actually not sure why it's happening. This log shouldn't ever happen, which is why it's a vague error message. It should be printing the `$result['errors']` array, which is what you're seeing. At this stage, `$result` is coming from the attempt it makes to save the post, but the only time `errors` gets populated when WordPress runs its own create or update methods.

To me, your error log looks like it's not up to date with the changes in this branch. It should contain a `method_match` parameter in that array if there is a prematch field.

I'm not entirely sure what to tell you at this point. I'm assuming you have already resaved the field map and cleared the plugin cache.

Are you seeing any PHP errors in your server logs for any of this?

**Comment by jonathanstegall** [comment]
I'm curious about possible ways to move this forward. Here's what I can think of, off the top of my head.

If you'd like to do further testing before release:
1. You could re-download the plugin from [this branch](https://github.com/MinnPost/object-sync-for-salesforce/tree/200-prematch-against-meta-fields) just to make sure (no composer should be needed for this branch, now).
2. You could then resave your existing fieldmap, and/or create a new fieldmap with conditions where this branch would apply.
3. Either way, you could check the `wp_object_sync_sf_field_map` table in the database. Make sure it has a `pull_to_drafts` field with a value of `1` and a `version` field with a value of 1.5.0.
4. You could also search the `fields` column in the same table for the value "match". A SQL query to do this would be `select * from wp_object_sync_sf_field_map WHERE fields LIKE '%"match"%';` and if it does not return any results when a prematch field is selected, the data is not stored in an up to date way.

This would allow you to make sure the code and data structure is up to date. Then you could see if it's still behaving as in the log message above, either with a resaved fieldmap and/or a new fieldmap.

If you don't want to do further testing, we could:

1. Release a new version of the plugin.
2. It's possible your plugin is missing something that would occur in the activation hook if you installed the update from the plugin directory (if this turns out to be the case, it'd be great to find out what it was that required this).

It's certainly possible that some other factor is causing the issue for you, and perhaps it would be easier to find it after a new release. But I'm inclined to think it's worthwhile since the worst case scenario appears to be that in some case the bug exists as it currently does without being fixed, while in others it is fixed.

If I don't hear from you in by early next week I'll go ahead and release this as an update release and I'll go from there.

**Comment by nodakjones** [comment]
1. I re-downloaded the plugin.
2. I deleted the existing field mapping and re-added a new one
3. Version is 1.5.0.  I’m pulling in the posts now as publish.  So, I would think pull_to_drafts should be 0?  Either way I’ve performed a test with the pull_to_drafts set to 0 and to 1
4. Running the sql query you provided does return the single record I have in the wp_object_sync_sf_field_map table.

Things still aren't working. Each time I edit the record in SF it creates a new record in WP.  The logs say this:

Success: Create WordPress duplexes with ID of 28865 (Salesforce Duplex__c Id of a00f400000E4QQcAAN)
Success: Create WordPress duplexes with ID of 28860 (Salesforce Duplex__c Id of a00f400000E4QQcAAN)

You will notice that in each case the SF record id is the same.  I’m seeing that SF record id is correctly being stored each time in the post meta.  

It seems like you should be able to replicate my case:

1.  I’m using a custom post type (shouldn’t matter but just to make sure)
2.  I have a simple mapping
	* Mapping from my custom object in SF to my custom post type in WP
	* Date field to trigger pull: Last Modified Date
	* Fieldmap - sf id ( this is set the Salesforce Key), name, status (this is a formula field in SF set to publish so that we are confusing issue with drafts)
	* I have all fields direction set from Salesforce to WordPress
	* action triggers are Salesforce create, Salesforce update, Salesforce delete
	* I’ve tested with pull_to_draft checked and unchecked
3.  Create a new record in the salesforce object.  I see new record come to WP and it correctly has the sf id post meta field populated
4.  Edit the SF record, new post record is created in WP instead of editing the existing record.

On October 5, 2018 at 1:30:30 PM, Jonathan Stegall (notifications@github.com) wrote:

I'm curious about possible ways to move this forward. Here's what I can think of, off the top of my head.

If you'd like to do further testing before release:

You could re-download the plugin from this branch just to make sure (no composer should be needed for this branch, now).
You could then resave your existing fieldmap, and/or create a new fieldmap with conditions where this branch would apply.
Either way, you could check the wp_object_sync_sf_field_map table in the database. Make sure it has a pull_to_drafts field with a value of 1 and a version field with a value of 1.5.0.
You could also search the fields column in the same table for the value "match". A SQL query to do this would be select * from wp_object_sync_sf_field_map WHERE fields LIKE '%"match"%'; and if it does not return any results when a prematch field is selected, the data is not stored in an up to date way.
This would allow you to make sure the code and data structure is up to date. Then you could see if it's still behaving as in the log message above, either with a resaved fieldmap and/or a new fieldmap.

If you don't want to do further testing, we could:

Release a new version of the plugin.
It's possible your plugin is missing something that would occur in the activation hook if you installed the update from the plugin directory (if this turns out to be the case, it'd be great to find out what it was that required this).
It's certainly possible that some other factor is causing the issue for you, and perhaps it would be easier to find it after a new release. But I'm inclined to think it's worthwhile since the worst case scenario appears to be that in some case the bug exists as it currently does without being fixed, while in others it is fixed.

If I don't hear from you in by early next week I'll go ahead and release this as an update release and I'll go from there.

**Comment by jonathanstegall** [comment]
Have you already tried with your "sf id" field as a prematch field instead of as a Salesforce key field? That is the main difference I'm seeing.

**Comment by nodakjones** [comment]
I have both the prematch and sf key field checked on the id in the mapping. 

Now, in the log when I create the record in SF I see the following:

Error syncing: Upsert to WordPress (Salesforce Duplex__c Id a00f400000E4QbjAAF)
Success: Upsert WordPress duplexes with ID of 28899 (Salesforce Duplex__c Id of a00f400000E4QbjAAF)


Then when I update the same record in SF, I see the following in the log:

Error syncing: Upsert to WordPress (Salesforce Duplex__c Id a00f400000E4QbjAAF)


On October 8, 2018 at 8:36:05 AM, Jonathan Stegall (notifications@github.com) wrote:

Have you already tried with your "sf id" field as a prematch field instead of as a Salesforce key field? That is the main difference I'm seeing.

**Comment by jonathanstegall** [comment]
Ugh, I think I found/fixed the issue. I was able to have the same problem anyway, and fix it. I think I forgot to commit some lines to the git repo that I had and lost, so if it works, thanks!

Anyway, if you can download the `wordpress.php` file ([here's](https://raw.githubusercontent.com/MinnPost/object-sync-for-salesforce/200-prematch-against-meta-fields/classes/wordpress.php) the raw code URL), let me know if that fixes it for you.

**Comment by nodakjones** [comment]
I replaced the wordpress.php file.  Now, not getting the error in the log.  However, still upserting to a new WP post when editing the SF record instead of changing the existing WP post.

Success: Upsert WordPress duplexes with ID of 29049 (Salesforce Duplex__c Id of a00f400000E4R75AAF)
Success: Upsert WordPress duplexes with ID of 29045 (Salesforce Duplex__c Id of a00f400000E4R75AAF)


On October 8, 2018 at 12:09:32 PM, Jonathan Stegall (notifications@github.com) wrote:

Ugh, I think I found/fixed the issue. I was able to have the same problem anyway, and fix it. I think I forgot to commit some lines to the git repo that I had and lost, so if it works, thanks!

Anyway, if you can download the wordpress.php file (here's the raw code URL), let me know if that fixes it for you.

**Comment by jonathanstegall** [comment]
Okay. Here's what is working for me. Maybe we'll find something revelatory:

1. I have a custom post type called "apps" that is mapped to the Salesforce Lead object.
2. I'm using CMB2 to create these custom fields: First Name, Last Name, Company, Lead ID, and Post Status. Each is mapped to its corresponding field on the Lead object with Salesforce to WordPress as its direction.
3. Post Status in Salesforce has a default value of "publish"
4. The Lead ID field has Prematch checked.
5. Triggers checked are Salesforce create, Salesforce update, Salesforce delete.

I cleared the plugin cache after adding the post status and lead ID fields, as I was previously matching on the company field.

When I create a new lead in Salesforce, I get this log:

> Success: Upsert WordPress app with ID of 306 (Salesforce Lead Id of 00QW0000007I9oyMAC)

When I update that same lead in Salesforce, changing the values for first name, last name, and company, I get this log:

> Success: Update WordPress app with ID of 306 (Salesforce Lead Id of 00QW0000007I9oyMAC)

I can try with a custom Salesforce object. I don't foresee that making a difference, but it's worth a shot. Do you see any other differences?

**Comment by jonathanstegall** [comment]
The direction for all my fields is Salesforce to WordPress. I do not have Salesforce Key checked, but I do have Prematch checked. As you mentioned earlier from the docs, Salesforce Key doesn't do anything on pull operations.

**Comment by nodakjones** [comment]
Yes, I was just making sure.  I have the same settings but it always creating the new wp post instead of editing.

On October 8, 2018 at 2:36:37 PM, Jonathan Stegall (notifications@github.com) wrote:

The direction for all my fields is Salesforce to WordPress. I do not have Salesforce Key checked, but I do have Prematch checked. As you mentioned earlier from the docs, Salesforce Key doesn't do anything on pull operations.
