### ISSUE TITLE
Version 1.8.6 Update Error

### ISSUE THREAD

**Issue by Ethanb00** [MinnPost/object-sync-for-salesforce#273]
**Describe the bug**
I have been successfully using the plugin on v1.5.2 but when I updated to the lasted version, I got a nasty error that brought WP into a full error state (requiring me to deactivate all plugins via renaming the plugins folder). 

**To Reproduce**
1. Go to plugins with Version 1.5.2 installed
2. Click on update for the plugin
3. Refresh the page

**Expected behavior**
A completed update w/o error state 

**Screenshots**
![image](https://user-images.githubusercontent.com/5893479/59281506-65c3d900-8c35-11e9-8297-975a65c1ff7e.png)

**Environment (please complete the following information):**
 - WordPress Version: both 5.0 and 5.2.1
 - Other relevant plugins
   - Advanced Custom Forms v5.7.7
   - FacetWP v3.2.12
   - WP All Import - ACF Add-On v3.1.9
   - WP All Import Pro v4.5.5
   - UpdraftPlus - Backup/Restore v2.13.12.24
   - Snazzy Maps v1.1.5
   - Gravity Forms v2.4.4
   - Gravity Forms Utility v2.4.2
   - Gravity Forms MailChimp Add-On v4.5
   - Formidable Forms Pro v3.04.01
   - Formidable Forms v3.06

 
 - PHP Version 7.1.30

**Additional context**
It was working fine prior to trying to update. I also did the standard "turn all plugins off and slowly reenable them" and Object Sync is definitely the source. I do want to say thank you for making the plugin, it's an awesome tool, and a lifesaver for the project I've got it working with. 

Many thanks for any help you can offer.

**Comment by Ethanb00** [comment]
mini update: I downloaded and installed the 1.7 release (since that was the one that was pre-SOAP updates and it works fine.

**Comment by jonathanstegall** [comment]
I'll try to set up a site with an older version of this plugin and go through the update steps. A lot changed between 1.5 and 1.8, but I am not sure how this would happen so I need to watch it.

**Comment by Ethanb00** [comment]
Thank you, @jonathanstegall 

Please let me know if I can help!

**Comment by jonathanstegall** [comment]
@Ethanb00 thank you. Now that I'm looking into it further, I wonder if this is because your PHP install does not have the `SoapClient`. It never occurred to me but I suppose it's possible that there are hosts without Soap enabled, AND it's certainly possible that the Salesforce folks didn't build in a check for the existence of that class when they built out their library.

I'd love some help verifying this if you would be willing.

If so, here's what I'd like to try:

1. Do a `phpinfo();` call. Check for the existence of Soap. It would be something like the attached image if you do have it enabled (although I suspect you don't have it enabled, and that is the source of the problem)

![image](https://user-images.githubusercontent.com/435342/59364204-14325180-8cfc-11e9-9ebf-9baaee3b3d2a.png)

2. If you do NOT have Soap enabled, I'd like to try a fix and see if it works. If it does, I'll release it in a plugin update as soon as I can get it all set up (probably today or tomorrow). Open up the `classes/salesforce_soap_partner.php` file. In line 29, add this code:

```
if ( ! class_exists( 'SoapClient' ) ) {
    return;
}
```

My hope is that the plugin would just stop trying to load Soap, which certainly isn't required for the vast majority of the plugin's functionality, and go on about the rest of its business.

You'd unfortunately have to upgrade the plugin to 1.8.6 to test this, so I understand if you'd rather wait for the fix. I can try to test missing Soap in other ways if so.

**Comment by Ethanb00** [comment]
Looks like you are right on the money with the missing PHP SOAP extension. 

where it should be, but is not:
![image](https://user-images.githubusercontent.com/5893479/59373083-e575a480-8d16-11e9-8778-f53a8b3be949.png)

For your fix, would I upgrade to 1.8.6 (making the site go to a 500 error and add the code the via ssh/ftp), or make the update with the version I have installed now and then update the plugin?

Thanks!
-E

**Comment by Ethanb00** [comment]
Hey @jonathanstegall, two things:

1) I tried your fix and, unfortunately, it caused the site to go to the same error state as before. 

2) It's mostly irrelevant since I was able to solve the issue by managing to geat the SOAP extension enabled. 

After trying 1600000 different ways of installing and enabling php-soap from the CLI, I followed some random thing from a search on google, which, amazingly, works. 

In case it comes up for anyone else who is using WHM/cPanel, in WHM, under Software, select EasyApache, edit the cpanel default profile and toggle SOAP on. 

Sorry about the trouble and I appreciate the time to look into it!

**Comment by jonathanstegall** [comment]
@Ethanb00 so when you tried the fix, did you put the code I mentioned up after updating to 1.8.6 and then it was still broken?

Just want to make sure. There may be more aggressive ways I need to check for the existence of Soap but I want to make sure that you had an updated version, and then that still it didn't work with the fix.

If I can figure out a way to verify a fix that works, I'd like to add it to the plugin since Soap is rather optional anyway.

**Comment by Ethanb00** [comment]
@jonathanstegall I tried the fix on both 1.7 and 1.8.6 and I added the code you shared by taking what was previously on line 29 and pushing that down to insert the code. 

I agree with you that it would be ideal to find out a way to navigate around the Soap issue. 

I should be able to continue testing stuff on my sandbox/dev server (which I did not enable Soap on).

Let me know if you'd like me to try anything.

**Comment by Ethanb00** [comment]
oh, and I should mention, your code for checking if the SoapClient exists is still in my salesforce_soap_partner.php file (but I don't know if it's doing anything right now since Soap is active)

**Comment by jonathanstegall** [comment]
@Ethanb00 I made a pull request with a more thorough check for Soap's existence. But again I'm not entirely sure if it will work; I don't have good access to a server without Soap.

But if you could install these changes on a 1.8.6 version of the plugin on that stage server, we could find out.

**Comment by SaschaLoeffler** [comment]
Hi @jonathanstegall today i installed the current version of this plugin and received the same error message mentioned from ethan as SOAP is not active on our server. I also tried to integrate your changes but actually it was too complex for me. When do you think will you be able to provide us a fixed version?

**Comment by jonathanstegall** [comment]
@SaschaLoeffler It’s unlikely that I’ll release that as a fix until I can verify that it works. I don’t have access to a php server that doesn’t have SOAP installed on it, so it may be some time.

**Comment by SaschaLoeffler** [comment]
If you want, I can provide you access to our server. It is located at
bplaced.net and we use the pro version that doesn't support SOAP

Jonathan Stegall <notifications@github.com> schrieb am Mi., 3. Juli 2019,
19:04:

**Comment by jonathanstegall** [comment]
@saschaloeffler no, we don’t offer that kind of support. That is, I don’t log in to other people’s servers for free. What you could do is download this branch of the repository as a zip file and install it on your server and see if it works.

**Comment by SaschaLoeffler** [comment]
Hi Jonathan, i am new to github so sorry for asking such a bad question. I
downloaded all the 4 files from here
https://github.com/MinnPost/object-sync-for-salesforce/pull/274/files  and
uploaded them to my server, but i still receive the same error.

Sascha Löffler
Am Fürstengarten 13
72379 Hechingen
Mobil: 01578 4055433



Am Mi., 3. Juli 2019 um 22:51 Uhr schrieb Jonathan Stegall <
notifications@github.com>:

**Comment by jonathanstegall** [comment]
@SaschaLoeffler I've added a few additional changes to only try to load Soap if the admin setting has been enabled. Feel free to try uploading from the pull request again, and see if that resolves the error.
