### ISSUE TITLE
Make error handling consistent

### ISSUE THREAD

**Issue by jonathanstegall** [MinnPost/object-sync-for-salesforce#5]
There are places where we create a SalesforceException instance and other places where we create a log entry.

Feels like this needs to be more intentional than it is. Need to understand which to do when and why.

**Comment by benlk** [comment]
After examining where the plugin creates SalesforceExceptions and where it uses Salesforce_Logging, I think the rule should be:

- if the event is serious enough to be displayed to the user of the plugin, use a SalesforceException as they'll get caught and put in the admin interface.
- if the event is not going to be displayed to the user, put it in Salesforce_Logging, where it may end up in the database:
    - usual behavior (successes)
    - errors that the plugin will recover from

If you agree, then we need to add some more success logging for more-complete success coverage.

-------

## Notes on logging code patterns

### On the definition of `$logging`

Object_Sync_Salesforce::logging() assumes that the files loaded by it contain the WP_Logging class: https://github.com/MinnPost/object-sync-for-salesforce/blob/4b63e0beccbe987fa13f4aa722826efcbf7b3bac/object-sync-for-salesforce.php#L197-L203 If they do not, then this method fails, causing Object_Sync_Salesforce::__construct() to fail, causing the plugin to fail.

### How `$logging` is usually used

In code, we often have this pattern:

	if ( isset( $this->logging ) ) {
		$logging = $this->logging;
	} elseif ( class_exists( 'Salesforce_Logging' ) ) {
		$logging = new Salesforce_Logging( $this->wpdb, $this->version, $this->text_domain );
	}
	$logging->setup(
		__( $title, $this->text_domain ),
		print_r( $result, true ),
		0,
		0,
		$status
	);

This pattern does not work if `$logging` was set to something other than a `Salesforce_Logging` or `WP_Logging` instance. It's probably a safe assumption, though, so why bother with the `if ( isset() ) {} else {}` piece when `$logging` in the current class was inherited from `Object_Sync_Salesforce`?

### Notes on how `Salesforce_Logging::setup()` is called

The arguments on [`Salesforce_Logging::setup()`](https://github.com/MinnPost/object-sync-for-salesforce/blob/master/classes/logging.php#L185) are five:

- `$title`
- `$message`
- `$trigger`
- `$parent`
- `$status`

These fields correspond to the arguments on [`Salesforce_Logging::add()`](https://github.com/MinnPost/object-sync-for-salesforce/blob/master/classes/logging.php#L208) and thence to [`WP_Logging::add()`](https://github.com/pippinsplugins/WP-Logging):

- `$title`
- `$message`
- `$parent`

The `status` parameter is checked against `Salesforce_Loggin::statuses_to_log`, which is an array of options retrieved from `get_option( 'object_sync_for_salesforce_statuses_to_log', array() );`.

If that option is an empty array, then according to the `Salesforce_Logging` method `setup()` no logs will ever be written.

`setup()` then compares the trigger to `get_option( 'object_sync_for_salesforce_triggers_to_log', array() );` (not to a class property, but to the results of the get_option call). 

Those options are configured in the admin; they default to no logging.

Assuming that both of those conditionals pass, the method `setup()` calls the method `add( $title = '', $message = '', $parent = 0, $type = 'salesforce' );` which [creates the actual log event](https://github.com/MinnPost/object-sync-for-salesforce/blob/master/classes/logging.php#L208-L219) using the [`insert_log()` method of WP_Logging](https://github.com/pippinsplugins/WP-Logging#recording-log-entries). Without delving too deeply, this looks like it's just creating a post with the title `$title`, the post_content `$message`, and the post_parent `$parent`. `$log_type` is [set as a term in the wp_log_type taxonomy on the post](https://github.com/pippinsplugins/wp-logging/blob/master/WP_Logging.php#L275), and `Salesforce_Logging::add()` ensures that the log type is always the type 'salesforce'.

## List of logging places and types, and some commentary

- Salesforce::api_http_request(): debug for every API request
- Salesforce::http_request(): error if curl fails
- Salesforce::http_request(): error for Salesforce errorCode
- Salesforce::http_request(): error if an HTTP request results in an error
- Salesforce_Mapping::create_object_map(): error if mapping a WP object to an invalid Salesforce ID 0
- Salesforce_Mapping::create_object_map(): error if mapping a WP object to a Salesforce ID when there is already a WP object mapped to that Salesforce ID
- Salesforce_Mapping::load_by_salesforce(): error if, when retrieving WP objects by Salesforce ID, multiple WP objects are returned. In this case, load_by_salesforce returns the first object instead of returning both.
- Salesforce_Pull::get_updated_records(): error if, when pulling updated records from Salesforce, Salesforce returns an errorCode.
- Salesforce_Pull::salesforce_pull_process_records(): error if, when syncing WP objects and Salesforce objects, there is no Salesforce object id in the mapping that we got from the DB with the Salesforce_Mapping object passed to `new Salesforce_Pull` in `Object_sync_Salesforce::pull()`
- Salesforce_Pull::salesforce_pull_process_records(): error if, when deleting wordpress objects, wordpress generates a WordpressException indicating that WP failed to delete an object. If there's more than one field mapping, exceptions are held. If there's only one mapping, the exception is thrown, and then this exception is incorporated into the exception that this method will throw. (It sums all the exceptions and then throws one huge exception at the end of the method.)
- Salesforce_Pull::salesforce_pull_process_records(): success if the delete had no errors
- Salesforce_Pull::salesforce_pull_process_records(): notice that the delete was aborted because other mappings also use this WP object, and while the Slaesforce row in the DB and the mapping row were deleted, the WP object won't be.
- Salesforce_Pull::salesforce_pull_process_records(): error if there are Salesforce mappings that have a Wordpress ID of 0, which means that the mapping wasn't constructed correctly in the admin
- Salesforce_Pull::salesforce_pull_process_records(): notice if, while processing a record from Salseforce, for a mapping, we are creating or updating a mapping, if we can prematch with another mapping, if there is not already known to be a mapping associated with this salesforce ID, if there is a mapping associated with this wordpress ID, then there is already a wordpress object and mapping and salesforce object and we shouldn't create a new mapping between the two objects.
- Salesforce_Pull::salesforce_pull_process_records(): error if while creating or updating a new mapping, a WordpressException occurs.
- Salesforce_Pull::salesforce_pull_process_records(): success if when creating or updating a new mapping, no errors occur
- Salesforce_Pull::salesforce_pull_process_records(): error if when creating or updating a new mapping, a non-exception error occurred in the Wordpress::object_create() method.
- Salesforce_Pull::salesforce_pull_process_records(): success if, when updating a known-existing record, the process succeeds.
- Salesforce_Pull::salesforce_pull_process_records(): error if, while updating a known-existing records, a WordpressException occurs.
- Salesforce_Push::salesforce_push_object_crud(): error if, when attempting to push to salesforce, we have no wordpress ID. Immediately after, this method calls `return` with no return.
- Salesforce_Push::salesforce_push_sync_rest(): error if, while deleting mapped objects on SF, a SalesforceException is caught.
- Salesforce_Push::salesforce_push_sync_rest(): success if, when deleting mapped objects on SF, no exceptions occur.
- Salesforce_Push::salesforce_push_sync_rest(): notice if, when deleting mapped objects on SF, the SF record was not deleted because there were multiple WordPress IDs matched to the Salesforce ID.
- Salesforce_Push::salesforce_push_sync_rest(): error if, while upserting or creating an object on SF, a SalesforceException is caught.
- Salesforce_Push::salesforce_push_sync_rest(): success if the response of the API request has no 'errorCode'.
- Salesforce_Push::salesforce_push_sync_rest(): error if the response of the API request has an 'errorCode'
- Salesforce_Push::salesforce_push_sync_rest(): notice if the mapping object was last synced in the future of the present time. <- **should this be an error?**
- Salesforce_Push::salesforce_push_sync_rest(): success if an object_update call to the Salesforce API doesn't fail.
- Salesforce_Push::salesforce_push_sync_rest(): error if, while updating an object on SF, a SalesforceException is caught.
- Wordpress::user_upsert(): error if, when creating/updating a Wordpress user, no WP user ID was returned (no user now exists)
- Wordpress::post_upsert(): error if, when creating/updating a WordPress post, no WP post ID was returned (no user now exists)
- Wordpress::attachment_upsert(): error if, when creating/updating a WordPress attachment, no attachment (post) IID was returned (no attachment exists)
- Wordpress::term_upsert(): error if, when creating/updating a WordPress term, no term ID was returned (no 
- Wordpress::comment_upsert(): notice if, when creating/updating a WordPress comment, multiple WordPress comments exist for a given Salesforce ID. <- **Should this be an error?**
- Wordpress::comment_upsert(): error if, when creating/updating a WordPress comment, no comment ID was returned (no comment exists)
- Wordpress::

The Wordpress class methods don't have success logging.

## Exceptions

A list of places that the plugin uses exceptions:

- [Wordpress_Salesforce_Admin::show_admin_post()](https://github.com/MinnPost/object-sync-for-salesforce/blob/master/classes/admin.php#L281-L284): replaces admin page contents with message contents of caught SalesforceException or Exception
- [Salesforce::api_call](https://github.com/MinnPost/object-sync-for-salesforce/blob/master/classes/salesforce.php#L202-L208): Without catching in this function, throws SalesforceException if:
	- the API call returns an error
	- the API call has an errorCode
	- the API's response has a refresh code, triggering an API call whose response code is not in the array of success codes in `Salesforce::success_codes`
	- the API's response does not have a response code that is a success code or a refresh code
- [Salesforce::refresh_token()](https://github.com/MinnPost/object-sync-for-salesforce/blob/master/classes/salesforce.php#L516): Throws a SalesforceException when there's no refresh token, I'm guessing this is only used after we've set up the plugin and the plugin is in a state where it beieves that it has a refresh token.
- [Salesforce::refresh_token()](https://github.com/MinnPost/object-sync-for-salesforce/blob/master/classes/salesforce.php#L538): Throws a SalesforceException when trying to get a new access token but the response code is anything other than `200`.
- [Salesforce::refresh_token()](https://github.com/MinnPost/object-sync-for-salesforce/blob/master/classes/salesforce.php#L544): Throws a SalesforceException when the response's data array contains an index 'error'
- [Salesforce::set_identity()](https://github.com/MinnPost/object-sync-for-salesforce/blob/master/classes/salesforce.php#L568): Throws a SalesforceException when trying to retrieve the Salesforce identity token when the response code is not `200`.
- [Salesforce::request_token()](https://github.com/MinnPost/object-sync-for-salesforce/blob/master/classes/salesforce.php#L626): Throws a SalesforceException when trying to get an access toaken during the OAuth workflow when the response code is not `200`.

Let it be noted that `SalesforceException` and `SalesforcePullException` are empty extensions of the base `Exception`. https://github.com/MinnPost/object-sync-for-salesforce/blob/master/classes/salesforce.php#L1180-L1184

And so is WordpressException: https://github.com/MinnPost/object-sync-for-salesforce/blob/master/classes/wordpress.php#L2399

**Comment by jonathanstegall** [comment]
Great notes. I'll respond a bit here and we can go from there.

1. I think I agree with your rule. It's probably worth specifying more clearly which errors get an exception vs a log though. Especially with the added complexity that many events happen during cron runs, and it's possible there wouldn't be a user on the admin side to see them. So I think it's worth being fairly specific about this. But I don't really have an answer for it, so I'm open to your thoughts. I mostly kept the Drupal Salesforce module's conventions for log vs exception unless they didn't have an equivalent to something I was doing, but there's no reason we should continue to do that if there's a better pattern. It just hasn't been thought out as well.

2. On the `$logging` class, I did it this way because sometimes it didn't work otherwise. But that was months ago. Feel free to test including the class without the `if` `else` if you want. It's certainly possible I just didn't know what I was doing.

3. You're exactly right about how the log entries get created. The only thing I'd add is that the log content type does not get displayed in the admin UI (although it does get added to the database) unless `define( 'WP_DEBUG', true );` is present in `wp-config.php`. You can see this in [the logging class](https://github.com/pippinsplugins/wp-logging/blob/master/WP_Logging.php#L155). Presumably it could be overwritten in the extend class, but I have not looked into this yet.

4. Your list seems fine. If you think the two that are currently notices would be better served as errors, I'm ok with that. I don't feel strongly about either of those.

5. The Exceptions aren't doing a whole lot currently. I don't really know what they should do, I guess.

**Comment by benlk** [comment]
1. The rule could be that _everything_ gets an exception, and that most exceptions get caught and converted to logs.
2. I'll try this, but the current pattern doesn't cause problems and so it should be a lower-priority issues.
3. Do you want to display logs in the admin at all times, or perhaps make that toggleable based on the "debug mode" checkbox?
4. https://github.com/MinnPost/object-sync-for-salesforce/pull/85
5. That's okay. I was mostly making note of it just so we were clear how they didn't differ from the standard Exception.

**Comment by jonathanstegall** [comment]
@benlk 

1. That would indeed be a ton of work. Let's not do that, at least in v1. 
2. I agree. Let's not worry about that for now.
3. I am open to your thoughts about this. Currently the "debug mode" checkbox logs a lot more stuff (all the SF API results), which obviously could be confusing. The logs that run when WordPress itself is in debug mode are leaner. I think they could be visible at all times, but I am totally open to your thoughts about this. I think if they are visible all the time, maybe it should be only for admin users.
4. Great.
6. Works for me.

**Comment by benlk** [comment]
Regarding point 3, the logs entry appears in the sidebar if the current user has the capability `configure_salesforce`: https://github.com/MinnPost/object-sync-for-salesforce/blob/master/classes/logging.php#L56 We ignore `WP_DEBUG` entirely. So they're always visible when the "Enable Logging?" checkbox is checked, but only for admins.

I think that matches what you describe, though if we wanted we could make [Object_Sync_Sf_Logging->set_log_visibility()](https://github.com/MinnPost/object-sync-for-salesforce/blob/master/classes/logging.php#L69) not run if `WP_DEBUG` is true, effectively makign the logs appear to all users if `WP_DEBUG` is true.

**Comment by jonathanstegall** [comment]
@benlk I don't have a strong opinion about that either way, I think. I don't know if the logs would be useful to people who aren't admins, but maybe. I am fine with your best opinion on this, whatever it is.

**Comment by jonathanstegall** [comment]
Closing this for now, under the assumption that error handling is okay until we find out that there are problems we haven't identified.
